name: LaTeX

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v2
    - name: Compile LaTeX beamer document
      uses: xu-cheng/latex-action@v2
      with:
        root_file: template.tex
        latexmk_use_lualatex: true
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: template
        path: template.pdf
